name: my_trip
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.5.0'

dependencies: 
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  flutter: 
    sdk: flutter
  flutter_svg: ^1.1.0
  flutter_phosphor_icons: ^0.0.1+6
  ##introduction_screen: ^3.0.2   // onboarding screen
#  flutter_native_splash: 2.2.4
  flutter_screenutil: ^5.5.3+2
  get_storage: ^2.0.3
  http: ^0.13.4
  intl: ^0.17.0
  ##flutter_secure_storage: ^5.0.2   // secure storage
dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-VariableFont_wght.ttf

