name: my_trip
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  flutter_svg: ^1.0.3
  flutter_phosphor_icons: ^0.0.1+6
  ##introduction_screen: ^3.0.2   // onboarding screen
  ##flutter_native_splash: ^2.1.6 // splash screen
  flutter_screenutil: ^5.4.0+1
  get_storage: ^2.0.3
  http: ^0.13.4
  ##flutter_secure_storage: ^5.0.2   // secure storage
dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-VariableFont_wght.ttf

